#!/bin/sh
#
# libvirt-wakeonlan, listens for wake on lan packets and starts libvirt based virtual machines
#
# chkconfig: 2345 20 80
# description:  listens for wake on lan packets and starts libvirt based virtual machines

### BEGIN INIT INFO
# Required-Start: $network 
### END INIT INFO

# Source function library.                                                                                                                        
. /etc/rc.d/init.d/functions                                                                                                                      
                                                                                                                                                  
exec="./libvirtwol.py"                                                                                                     
prog="/usr/share/libvirt-wakeonlan/libvirtwol.py"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog                                                                                                                               
                                                                                                                                                                                    
lockfile=/var/lock/subsys/$prog                                                                                                                                                     
pidfile=/var/run/$proc.pid                                                                                                                                                          
                                                                                                                                                                                    
start() {                                                                                                                                                                           
    [ -x $exec ] || exit 5                                                                                                                                                          
    echo -n $"Starting $prog: "                                                                                                                                                     
    # if not running, start it up here, usually something like "daemon $exec"
    cd /usr/share/libvirt-wakeonlan
    daemon $exec $LIBVIRTDWOL_INTERFACE                                                                                                                                                                   
    retval=$?                                                                                                                                                                       
    echo                                                                                                                                                                            
    [ $retval -eq 0 ] && touch $lockfile                                                                                                                                            
    return $retval                                                                                                                                                                  
}                                                                                                                                                                                   
                                                                                                                                                                                    
stop() {                                                                                                                                                                            
    echo -n $"Stopping $prog: "                                                                                                                                                     
    # stop it here, often "killproc $prog"                                                                                                                                          
    killproc $prog                                                                                                                                                                  
    retval=$?                                                                                                                                                                       
    echo                                                                                                                                                                            
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
